// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lottery/lottery/packet.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LotteryPacketData struct {
	// Types that are valid to be assigned to Packet:
	//	*LotteryPacketData_NoData
	//	*LotteryPacketData_RefundLotteryPacket
	//	*LotteryPacketData_SayhelloPacket
	//	*LotteryPacketData_BuyTicketPacket
	//	*LotteryPacketData_WinnerPickedPacket
	Packet isLotteryPacketData_Packet `protobuf_oneof:"packet"`
}

func (m *LotteryPacketData) Reset()         { *m = LotteryPacketData{} }
func (m *LotteryPacketData) String() string { return proto.CompactTextString(m) }
func (*LotteryPacketData) ProtoMessage()    {}
func (*LotteryPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_50262148acba624d, []int{0}
}
func (m *LotteryPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LotteryPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LotteryPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LotteryPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LotteryPacketData.Merge(m, src)
}
func (m *LotteryPacketData) XXX_Size() int {
	return m.Size()
}
func (m *LotteryPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_LotteryPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_LotteryPacketData proto.InternalMessageInfo

type isLotteryPacketData_Packet interface {
	isLotteryPacketData_Packet()
	MarshalTo([]byte) (int, error)
	Size() int
}

type LotteryPacketData_NoData struct {
	NoData *NoData `protobuf:"bytes,1,opt,name=noData,proto3,oneof" json:"noData,omitempty"`
}
type LotteryPacketData_RefundLotteryPacket struct {
	RefundLotteryPacket *RefundLotteryPacketData `protobuf:"bytes,2,opt,name=refundLotteryPacket,proto3,oneof" json:"refundLotteryPacket,omitempty"`
}
type LotteryPacketData_SayhelloPacket struct {
	SayhelloPacket *SayhelloPacketData `protobuf:"bytes,3,opt,name=sayhelloPacket,proto3,oneof" json:"sayhelloPacket,omitempty"`
}
type LotteryPacketData_BuyTicketPacket struct {
	BuyTicketPacket *BuyTicketPacketData `protobuf:"bytes,4,opt,name=buyTicketPacket,proto3,oneof" json:"buyTicketPacket,omitempty"`
}
type LotteryPacketData_WinnerPickedPacket struct {
	WinnerPickedPacket *WinnerPickedPacketData `protobuf:"bytes,5,opt,name=winnerPickedPacket,proto3,oneof" json:"winnerPickedPacket,omitempty"`
}

func (*LotteryPacketData_NoData) isLotteryPacketData_Packet()              {}
func (*LotteryPacketData_RefundLotteryPacket) isLotteryPacketData_Packet() {}
func (*LotteryPacketData_SayhelloPacket) isLotteryPacketData_Packet()      {}
func (*LotteryPacketData_BuyTicketPacket) isLotteryPacketData_Packet()     {}
func (*LotteryPacketData_WinnerPickedPacket) isLotteryPacketData_Packet()  {}

func (m *LotteryPacketData) GetPacket() isLotteryPacketData_Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (m *LotteryPacketData) GetNoData() *NoData {
	if x, ok := m.GetPacket().(*LotteryPacketData_NoData); ok {
		return x.NoData
	}
	return nil
}

func (m *LotteryPacketData) GetRefundLotteryPacket() *RefundLotteryPacketData {
	if x, ok := m.GetPacket().(*LotteryPacketData_RefundLotteryPacket); ok {
		return x.RefundLotteryPacket
	}
	return nil
}

func (m *LotteryPacketData) GetSayhelloPacket() *SayhelloPacketData {
	if x, ok := m.GetPacket().(*LotteryPacketData_SayhelloPacket); ok {
		return x.SayhelloPacket
	}
	return nil
}

func (m *LotteryPacketData) GetBuyTicketPacket() *BuyTicketPacketData {
	if x, ok := m.GetPacket().(*LotteryPacketData_BuyTicketPacket); ok {
		return x.BuyTicketPacket
	}
	return nil
}

func (m *LotteryPacketData) GetWinnerPickedPacket() *WinnerPickedPacketData {
	if x, ok := m.GetPacket().(*LotteryPacketData_WinnerPickedPacket); ok {
		return x.WinnerPickedPacket
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LotteryPacketData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LotteryPacketData_NoData)(nil),
		(*LotteryPacketData_RefundLotteryPacket)(nil),
		(*LotteryPacketData_SayhelloPacket)(nil),
		(*LotteryPacketData_BuyTicketPacket)(nil),
		(*LotteryPacketData_WinnerPickedPacket)(nil),
	}
}

type NoData struct {
}

func (m *NoData) Reset()         { *m = NoData{} }
func (m *NoData) String() string { return proto.CompactTextString(m) }
func (*NoData) ProtoMessage()    {}
func (*NoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_50262148acba624d, []int{1}
}
func (m *NoData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NoData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoData.Merge(m, src)
}
func (m *NoData) XXX_Size() int {
	return m.Size()
}
func (m *NoData) XXX_DiscardUnknown() {
	xxx_messageInfo_NoData.DiscardUnknown(m)
}

var xxx_messageInfo_NoData proto.InternalMessageInfo

// RefundLotteryPacketData defines a struct for the packet payload
type RefundLotteryPacketData struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *RefundLotteryPacketData) Reset()         { *m = RefundLotteryPacketData{} }
func (m *RefundLotteryPacketData) String() string { return proto.CompactTextString(m) }
func (*RefundLotteryPacketData) ProtoMessage()    {}
func (*RefundLotteryPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_50262148acba624d, []int{2}
}
func (m *RefundLotteryPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RefundLotteryPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RefundLotteryPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RefundLotteryPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundLotteryPacketData.Merge(m, src)
}
func (m *RefundLotteryPacketData) XXX_Size() int {
	return m.Size()
}
func (m *RefundLotteryPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundLotteryPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_RefundLotteryPacketData proto.InternalMessageInfo

func (m *RefundLotteryPacketData) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// RefundLotteryPacketAck defines a struct for the packet acknowledgment
type RefundLotteryPacketAck struct {
}

func (m *RefundLotteryPacketAck) Reset()         { *m = RefundLotteryPacketAck{} }
func (m *RefundLotteryPacketAck) String() string { return proto.CompactTextString(m) }
func (*RefundLotteryPacketAck) ProtoMessage()    {}
func (*RefundLotteryPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_50262148acba624d, []int{3}
}
func (m *RefundLotteryPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RefundLotteryPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RefundLotteryPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RefundLotteryPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundLotteryPacketAck.Merge(m, src)
}
func (m *RefundLotteryPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *RefundLotteryPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundLotteryPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_RefundLotteryPacketAck proto.InternalMessageInfo

// SayhelloPacketData defines a struct for the packet payload
type SayhelloPacketData struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *SayhelloPacketData) Reset()         { *m = SayhelloPacketData{} }
func (m *SayhelloPacketData) String() string { return proto.CompactTextString(m) }
func (*SayhelloPacketData) ProtoMessage()    {}
func (*SayhelloPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_50262148acba624d, []int{4}
}
func (m *SayhelloPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SayhelloPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SayhelloPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SayhelloPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayhelloPacketData.Merge(m, src)
}
func (m *SayhelloPacketData) XXX_Size() int {
	return m.Size()
}
func (m *SayhelloPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_SayhelloPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_SayhelloPacketData proto.InternalMessageInfo

func (m *SayhelloPacketData) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// SayhelloPacketAck defines a struct for the packet acknowledgment
type SayhelloPacketAck struct {
}

func (m *SayhelloPacketAck) Reset()         { *m = SayhelloPacketAck{} }
func (m *SayhelloPacketAck) String() string { return proto.CompactTextString(m) }
func (*SayhelloPacketAck) ProtoMessage()    {}
func (*SayhelloPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_50262148acba624d, []int{5}
}
func (m *SayhelloPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SayhelloPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SayhelloPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SayhelloPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayhelloPacketAck.Merge(m, src)
}
func (m *SayhelloPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *SayhelloPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SayhelloPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_SayhelloPacketAck proto.InternalMessageInfo

// BuyTicketPacketData defines a struct for the packet payload
type BuyTicketPacketData struct {
	LotteryId uint64     `protobuf:"varint,1,opt,name=lotteryId,proto3" json:"lotteryId,omitempty"`
	Price     types.Coin `protobuf:"bytes,2,opt,name=price,proto3" json:"price"`
	Creator   string     `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *BuyTicketPacketData) Reset()         { *m = BuyTicketPacketData{} }
func (m *BuyTicketPacketData) String() string { return proto.CompactTextString(m) }
func (*BuyTicketPacketData) ProtoMessage()    {}
func (*BuyTicketPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_50262148acba624d, []int{6}
}
func (m *BuyTicketPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BuyTicketPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BuyTicketPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BuyTicketPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyTicketPacketData.Merge(m, src)
}
func (m *BuyTicketPacketData) XXX_Size() int {
	return m.Size()
}
func (m *BuyTicketPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyTicketPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_BuyTicketPacketData proto.InternalMessageInfo

func (m *BuyTicketPacketData) GetLotteryId() uint64 {
	if m != nil {
		return m.LotteryId
	}
	return 0
}

func (m *BuyTicketPacketData) GetPrice() types.Coin {
	if m != nil {
		return m.Price
	}
	return types.Coin{}
}

func (m *BuyTicketPacketData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// BuyTicketPacketAck defines a struct for the packet acknowledgment
type BuyTicketPacketAck struct {
}

func (m *BuyTicketPacketAck) Reset()         { *m = BuyTicketPacketAck{} }
func (m *BuyTicketPacketAck) String() string { return proto.CompactTextString(m) }
func (*BuyTicketPacketAck) ProtoMessage()    {}
func (*BuyTicketPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_50262148acba624d, []int{7}
}
func (m *BuyTicketPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BuyTicketPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BuyTicketPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BuyTicketPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyTicketPacketAck.Merge(m, src)
}
func (m *BuyTicketPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *BuyTicketPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyTicketPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_BuyTicketPacketAck proto.InternalMessageInfo

// WinnerPickedPacketData defines a struct for the packet payload
type WinnerPickedPacketData struct {
	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (m *WinnerPickedPacketData) Reset()         { *m = WinnerPickedPacketData{} }
func (m *WinnerPickedPacketData) String() string { return proto.CompactTextString(m) }
func (*WinnerPickedPacketData) ProtoMessage()    {}
func (*WinnerPickedPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_50262148acba624d, []int{8}
}
func (m *WinnerPickedPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WinnerPickedPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WinnerPickedPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WinnerPickedPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WinnerPickedPacketData.Merge(m, src)
}
func (m *WinnerPickedPacketData) XXX_Size() int {
	return m.Size()
}
func (m *WinnerPickedPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_WinnerPickedPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_WinnerPickedPacketData proto.InternalMessageInfo

func (m *WinnerPickedPacketData) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WinnerPickedPacketData) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

// WinnerPickedPacketAck defines a struct for the packet acknowledgment
type WinnerPickedPacketAck struct {
}

func (m *WinnerPickedPacketAck) Reset()         { *m = WinnerPickedPacketAck{} }
func (m *WinnerPickedPacketAck) String() string { return proto.CompactTextString(m) }
func (*WinnerPickedPacketAck) ProtoMessage()    {}
func (*WinnerPickedPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_50262148acba624d, []int{9}
}
func (m *WinnerPickedPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WinnerPickedPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WinnerPickedPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WinnerPickedPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WinnerPickedPacketAck.Merge(m, src)
}
func (m *WinnerPickedPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *WinnerPickedPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_WinnerPickedPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_WinnerPickedPacketAck proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LotteryPacketData)(nil), "lottery.lottery.LotteryPacketData")
	proto.RegisterType((*NoData)(nil), "lottery.lottery.NoData")
	proto.RegisterType((*RefundLotteryPacketData)(nil), "lottery.lottery.RefundLotteryPacketData")
	proto.RegisterType((*RefundLotteryPacketAck)(nil), "lottery.lottery.RefundLotteryPacketAck")
	proto.RegisterType((*SayhelloPacketData)(nil), "lottery.lottery.SayhelloPacketData")
	proto.RegisterType((*SayhelloPacketAck)(nil), "lottery.lottery.SayhelloPacketAck")
	proto.RegisterType((*BuyTicketPacketData)(nil), "lottery.lottery.BuyTicketPacketData")
	proto.RegisterType((*BuyTicketPacketAck)(nil), "lottery.lottery.BuyTicketPacketAck")
	proto.RegisterType((*WinnerPickedPacketData)(nil), "lottery.lottery.WinnerPickedPacketData")
	proto.RegisterType((*WinnerPickedPacketAck)(nil), "lottery.lottery.WinnerPickedPacketAck")
}

func init() { proto.RegisterFile("lottery/lottery/packet.proto", fileDescriptor_50262148acba624d) }

var fileDescriptor_50262148acba624d = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4d, 0x8f, 0x93, 0x40,
	0x18, 0xc7, 0xa1, 0xcb, 0xe2, 0xf6, 0x31, 0xd9, 0xcd, 0x4e, 0xd7, 0x05, 0x37, 0x1b, 0x34, 0xb8,
	0x89, 0xf5, 0x32, 0x04, 0x8d, 0x37, 0x2f, 0x45, 0x0f, 0x9a, 0xa8, 0x69, 0xd0, 0xc4, 0x68, 0xbc,
	0xf0, 0x32, 0x56, 0xd2, 0xca, 0x90, 0x61, 0xaa, 0x72, 0xf7, 0x03, 0xf8, 0x39, 0xfc, 0x24, 0x3d,
	0xf6, 0xe8, 0xc9, 0x98, 0xf6, 0x8b, 0x18, 0x86, 0x41, 0x03, 0x83, 0x27, 0xe6, 0xe5, 0xff, 0xff,
	0xf1, 0xcc, 0xf3, 0x02, 0x97, 0x2b, 0xca, 0x39, 0x61, 0x95, 0xd7, 0x7e, 0x8b, 0x28, 0x59, 0x12,
	0x8e, 0x0b, 0x46, 0x39, 0x45, 0x27, 0xf2, 0x14, 0xcb, 0xef, 0xc5, 0xd9, 0x82, 0x2e, 0xa8, 0xb8,
	0xf3, 0xea, 0x55, 0x23, 0xbb, 0x70, 0x12, 0x5a, 0x7e, 0xa2, 0xa5, 0x17, 0x47, 0x25, 0xf1, 0x3e,
	0xfb, 0x31, 0xe1, 0x91, 0xef, 0x25, 0x34, 0xcb, 0x9b, 0x7b, 0xf7, 0xc7, 0x01, 0x9c, 0x3e, 0x6f,
	0x08, 0x73, 0x81, 0x7f, 0x12, 0xf1, 0x08, 0xf9, 0x60, 0xe6, 0xb4, 0x5e, 0xd9, 0xfa, 0x6d, 0x7d,
	0x7a, 0xfd, 0xbe, 0x85, 0x7b, 0x7f, 0xc3, 0x2f, 0xc5, 0xf5, 0x53, 0x2d, 0x94, 0x42, 0xf4, 0x1e,
	0x26, 0x8c, 0x7c, 0x58, 0xe7, 0x69, 0x87, 0x66, 0x8f, 0x84, 0x7f, 0xaa, 0xf8, 0x43, 0x55, 0x2b,
	0x81, 0x43, 0x18, 0xf4, 0x02, 0x8e, 0xcb, 0xa8, 0xfa, 0x48, 0x56, 0x2b, 0x2a, 0xc1, 0x07, 0x02,
	0x7c, 0x47, 0x01, 0xbf, 0xea, 0xc8, 0x24, 0xb3, 0x67, 0x46, 0x73, 0x38, 0x89, 0xd7, 0xd5, 0xeb,
	0xac, 0xde, 0x48, 0x9e, 0x21, 0x78, 0x57, 0x0a, 0x2f, 0xe8, 0xea, 0x24, 0xb0, 0x6f, 0x47, 0x6f,
	0x01, 0x7d, 0xc9, 0xf2, 0x9c, 0xb0, 0x79, 0x7d, 0x9a, 0x4a, 0xe8, 0xa1, 0x80, 0xde, 0x55, 0xa0,
	0x6f, 0x14, 0xa9, 0xe4, 0x0e, 0x40, 0x82, 0x23, 0x30, 0x9b, 0xca, 0xbb, 0x47, 0x60, 0x36, 0x79,
	0x77, 0xef, 0x81, 0xf5, 0x9f, 0x0c, 0xa2, 0x63, 0x18, 0x65, 0xa9, 0xa8, 0x9b, 0x11, 0x8e, 0xb2,
	0xd4, 0xb5, 0xe1, 0x7c, 0x40, 0x3a, 0x4b, 0x96, 0xee, 0x15, 0x20, 0x35, 0x5b, 0x8a, 0x7f, 0x02,
	0xa7, 0x5d, 0x55, 0x6d, 0xfd, 0xa6, 0xc3, 0x64, 0x20, 0x33, 0xe8, 0x12, 0xc6, 0xf2, 0x8d, 0xcf,
	0x5a, 0xc6, 0xbf, 0x03, 0xf4, 0x10, 0x0e, 0x0b, 0x96, 0x25, 0x44, 0x76, 0xc5, 0x4d, 0xdc, 0x34,
	0x27, 0xae, 0x9b, 0x13, 0xcb, 0xe6, 0xc4, 0x8f, 0x69, 0x96, 0x07, 0xc6, 0xe6, 0xd7, 0x2d, 0x2d,
	0x6c, 0xd4, 0xc8, 0x86, 0x6b, 0x09, 0x23, 0x11, 0xa7, 0x4c, 0x54, 0x7d, 0x1c, 0xb6, 0x5b, 0xf7,
	0x0c, 0x50, 0x2f, 0x8a, 0x3a, 0xb8, 0x47, 0x70, 0x3e, 0x9c, 0xe0, 0xfe, 0xdb, 0x10, 0x02, 0x63,
	0x5d, 0x12, 0x26, 0xe2, 0x19, 0x87, 0x62, 0xed, 0x5a, 0x70, 0x43, 0x75, 0xcf, 0x92, 0x65, 0xe0,
	0x6f, 0x76, 0x8e, 0xbe, 0xdd, 0x39, 0xfa, 0xef, 0x9d, 0xa3, 0x7f, 0xdf, 0x3b, 0xda, 0x76, 0xef,
	0x68, 0x3f, 0xf7, 0x8e, 0xf6, 0xce, 0x6a, 0x27, 0xf4, 0xeb, 0xdf, 0x59, 0xe5, 0x55, 0x41, 0xca,
	0xd8, 0x14, 0x43, 0xf6, 0xe0, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xf9, 0x43, 0xbe, 0xcb,
	0x03, 0x00, 0x00,
}

func (m *LotteryPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LotteryPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LotteryPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Packet != nil {
		{
			size := m.Packet.Size()
			i -= size
			if _, err := m.Packet.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *LotteryPacketData_NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LotteryPacketData_NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.NoData != nil {
		{
			size, err := m.NoData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *LotteryPacketData_RefundLotteryPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LotteryPacketData_RefundLotteryPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.RefundLotteryPacket != nil {
		{
			size, err := m.RefundLotteryPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *LotteryPacketData_SayhelloPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LotteryPacketData_SayhelloPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.SayhelloPacket != nil {
		{
			size, err := m.SayhelloPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *LotteryPacketData_BuyTicketPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LotteryPacketData_BuyTicketPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.BuyTicketPacket != nil {
		{
			size, err := m.BuyTicketPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *LotteryPacketData_WinnerPickedPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LotteryPacketData_WinnerPickedPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.WinnerPickedPacket != nil {
		{
			size, err := m.WinnerPickedPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *NoData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *RefundLotteryPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RefundLotteryPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RefundLotteryPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RefundLotteryPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RefundLotteryPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RefundLotteryPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *SayhelloPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SayhelloPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SayhelloPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SayhelloPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SayhelloPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SayhelloPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *BuyTicketPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BuyTicketPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BuyTicketPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Price.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPacket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.LotteryId != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.LotteryId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BuyTicketPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BuyTicketPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BuyTicketPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *WinnerPickedPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WinnerPickedPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WinnerPickedPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.User) > 0 {
		i -= len(m.User)
		copy(dAtA[i:], m.User)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.User)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *WinnerPickedPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WinnerPickedPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WinnerPickedPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LotteryPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Packet != nil {
		n += m.Packet.Size()
	}
	return n
}

func (m *LotteryPacketData_NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NoData != nil {
		l = m.NoData.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *LotteryPacketData_RefundLotteryPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RefundLotteryPacket != nil {
		l = m.RefundLotteryPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *LotteryPacketData_SayhelloPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SayhelloPacket != nil {
		l = m.SayhelloPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *LotteryPacketData_BuyTicketPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BuyTicketPacket != nil {
		l = m.BuyTicketPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *LotteryPacketData_WinnerPickedPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WinnerPickedPacket != nil {
		l = m.WinnerPickedPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *RefundLotteryPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovPacket(uint64(m.Id))
	}
	return n
}

func (m *RefundLotteryPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *SayhelloPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovPacket(uint64(m.Id))
	}
	return n
}

func (m *SayhelloPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *BuyTicketPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LotteryId != 0 {
		n += 1 + sovPacket(uint64(m.LotteryId))
	}
	l = m.Price.Size()
	n += 1 + l + sovPacket(uint64(l))
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *BuyTicketPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *WinnerPickedPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovPacket(uint64(m.Id))
	}
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *WinnerPickedPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LotteryPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LotteryPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LotteryPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &NoData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &LotteryPacketData_NoData{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefundLotteryPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &RefundLotteryPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &LotteryPacketData_RefundLotteryPacket{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SayhelloPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &SayhelloPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &LotteryPacketData_SayhelloPacket{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyTicketPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &BuyTicketPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &LotteryPacketData_BuyTicketPacket{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WinnerPickedPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &WinnerPickedPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &LotteryPacketData_WinnerPickedPacket{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NoData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NoData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NoData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RefundLotteryPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RefundLotteryPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RefundLotteryPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RefundLotteryPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RefundLotteryPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RefundLotteryPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SayhelloPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SayhelloPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SayhelloPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SayhelloPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SayhelloPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SayhelloPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BuyTicketPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BuyTicketPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BuyTicketPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LotteryId", wireType)
			}
			m.LotteryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LotteryId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BuyTicketPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BuyTicketPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BuyTicketPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WinnerPickedPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WinnerPickedPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WinnerPickedPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WinnerPickedPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WinnerPickedPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WinnerPickedPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
